### ISSUE TITLE
Improve commit messages

### ISSUE THREAD

**Issue by chibby0ne** [vaneguti110/train-animation#1]
At the moment the commit messages aren't really useful, and they repeat themselves without specifying why.

```
commit 23964bf5ee3ba8db995f23120a8ac9c0b5bdf83c (HEAD -> master, origin/master, origin/HEAD)
Author: Vanessa <vaneguti110@hotmail.com>
Date:   Fri Mar 2 16:21:15 2018 +0100

    add google font

commit 394b033582039f752cea70a096ca42b91a0139c3
Author: Vanessa <vaneguti110@hotmail.com>
Date:   Fri Mar 2 16:19:59 2018 +0100

    add the font

commit 19955960238b139e0938762c14c079677b667696
Author: Vanessa <vaneguti110@hotmail.com>
Date:   Fri Mar 2 16:19:26 2018 +0100

    add the font
```

I suggest following well known good practices for git commit messages such as the ones stated here:
https://chris.beams.io/posts/git-commit/

This will improve maintainability and will help people new to the repo understand the changes and history.

In the case of the given example we could have something like:

```
slowtransition: add google font to index.html
```

```
normaltransition: add google font to index.html
```

Or preferably since these commits are very small, squash all the commits related to adding fonts into one.

That is:

```
Add google fonts

The particular google font chosen is Nina, and it's used for both slow and normal transistions.
```

**Comment by vaneguti110** [comment]
thanks for the advice. I will put it on practice.
